<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Include common properties -->
<xacro:property name="camera_length" value="0.01" />
<xacro:property name="camera_width" value="0.1" />
<xacro:property name="camera_height" value="0.05" />

<!-- Links -->
   <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.1" x="${camera_length}" y="${camera_width}" z="${camera_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

<!-- Joints -->
<joint name="base_camera_joint" type="fixed">
    <parent link="mobile_base_link"/>
    <child link="camera_link"/>
    <origin xyz="${(base_length + camera_length) / 2.0} 0 0" rpy="0 0 0"/>
</joint>

</robot>