<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Define mobile base properties -->
<xacro:property name="base_length" value="0.6"/>
<xacro:property name="base_width" value="0.4"/>
<xacro:property name="base_height" value="0.2"/>
<xacro:property name="wheel_radius" value="0.1"/>
<xacro:property name="wheel_width" value="0.05"/>
<xacro:property name="caster_radius" value="0.05"/>

<!-- Links -->
<link name="base_footprint"/>

<link name="mobile_base_link">
    <visual>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="blue"/>
    </visual>
</link>

<xacro:macro name="wheel_link" params="prefix">
    <link name="${prefix}_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${-pi/2}"/>
            <material name="grey"/>
        </visual>
    </link>
</xacro:macro>

<xacro:wheel_link prefix="left"/>
<xacro:wheel_link prefix="right"/>

<link name="caster_wheel_link">
    <visual>
        <geometry>
            <sphere radius="${caster_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="grey"/>
    </visual>
</link>

<!-- Joints -->
<joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="mobile_base_link"/>
    <origin xyz="0 0 ${wheel_radius + base_height/2}" rpy="0 0 0"/>
</joint>

<joint name="left_wheel_joint" type="continuous">
    <parent link="mobile_base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="${-base_length/4} ${-(base_width + wheel_width)/2} ${-(base_height/2)}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
</joint>

<joint name="right_wheel_joint" type="continuous">
    <parent link="mobile_base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="${-base_length/4} ${(base_width + wheel_width)/2} ${-(base_height/2)}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
</joint>

<joint name="caster_wheel_joint" type="fixed">
    <parent link="mobile_base_link"/>
    <child link="caster_wheel_link"/>
    <origin xyz="${base_length/4} 0 ${-(caster_radius+base_height/2)}" rpy="0 0 0"/>
</joint>

</robot>