<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<gazebo reference="caster_wheel_link">
    <mu1 value="0.1"/>
    <mu2 value="0.1"/>
</gazebo>

<gazebo>
    <plugin
        filename="gz-sim-diff-drive-system"
        name="gz::sim::systems::DiffDrive">
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${base_width + 2*wheel_width/2}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <frame_id>odom</frame_id>
        <child_frame_id>base_footprint</child_frame_id>
        <topic>/cmd_vel</topic>
    </plugin>
</gazebo>

<gazebo>
    <plugin
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
        <joint_name>left_wheel_joint</joint_name>
        <joint_name>right_wheel_joint</joint_name>
        <joint_name>forearm_joint_to_arm_base</joint_name>
        <joint_name>hand_joint_to_forearm</joint_name>
    </plugin>
</gazebo>


</robot>