<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================= -->
  <!--       PROPERTIES          -->
  <!-- ========================= -->

  <xacro:property name="wheel_radius" value="0.119289"/>
  <xacro:property name="wheel_width" value="0.160767"/>

  <xacro:property name="roda_radius" value="0.038463"/>

  <xacro:property name="base_x" value="0.102772"/>
  <xacro:property name="base_y" value="-0.213746"/>
  <xacro:property name="base_z" value="-0.353914"/>

  <xacro:property name="left_wheel_x" value="0.342038"/>
  <xacro:property name="right_wheel_x" value="-0.136493"/>
  <xacro:property name="wheel_z" value="-0.119289"/>

  <xacro:property name="roda_x" value="0.102772"/>
  <xacro:property name="roda_y" value="-0.422475"/>
  <xacro:property name="roda_z" value="-0.045338"/>

  <!-- Masses -->
  <xacro:property name="base_mass" value="2.5"/>
  <xacro:property name="wheel_mass" value="0.35"/>
  <xacro:property name="roda_mass" value="0.2"/>


  <!-- ========================= -->
  <!--        ROOT FRAME         -->
  <!-- ========================= -->

  <link name="base_footprint"/>

  <!-- ========================= -->
  <!--     MOBILE BASE LINK      -->
  <!-- ========================= -->

  <link name="mobile_uvc_base_link">
    <visual>
      <geometry>
        <mesh filename="file:///home/linos/cad_projects/mobile/body.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="${base_x} ${base_y} ${base_z}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>

    <collision>
      <geometry>
        <box size="0.500 0.849993 0.4"/>
      </geometry>
      <origin xyz="0 0 ${-0.253914/2}" rpy="0 0 0"/>
    </collision>

    <!-- INERTIA (BOX) -->
    <xacro:box_inertia
        m="${base_mass}"
        x="0.500"
        y="0.849993"
        z="0.4"
        o_xyz="0 0 ${-0.253914/2}"
        o_rpy="0 0 0"/>
  </link>

  <!-- ========================= -->
  <!--       LEFT WHEEL          -->
  <!-- ========================= -->

  <link name="left_wheel_link">
    <visual>
      <geometry>
        <mesh filename="file:///home/linos/cad_projects/mobile/left_wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="${left_wheel_x} 0 ${wheel_z}" rpy="0 0 0"/>
      <material name="green"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="${wheel_width/2} 0 0" rpy="0 0 0"/>
    </collision>

    <!-- INERTIA (SPHERE) -->
    <xacro:sphere_inertia
        m="${wheel_mass}"
        r="${wheel_radius}"
        o_xyz="${wheel_width/2} 0 0"
        o_rpy="0 0 0"/>
  </link>

  <!-- ========================= -->
  <!--       RIGHT WHEEL         -->
  <!-- ========================= -->

  <link name="right_wheel_link">
    <visual>
      <geometry>
        <mesh filename="file:///home/linos/cad_projects/mobile/right_wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="${right_wheel_x} 0 ${wheel_z}" rpy="0 0 0"/>
      <material name="green"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="${-wheel_width/2} 0 0" rpy="0 0 0"/>
    </collision>

    <!-- INERTIA (SPHERE) -->
    <xacro:sphere_inertia
        m="${wheel_mass}"
        r="${wheel_radius}"
        o_xyz="${-wheel_width/2} 0 0"
        o_rpy="0 0 0"/>
  </link>

  <!-- ========================= -->
  <!--           RODA            -->
  <!-- ========================= -->

  <link name="roda_link">
    <visual>
      <geometry>
        <mesh filename="file:///home/linos/cad_projects/mobile/roda.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="${roda_x} ${roda_y} ${roda_z}" rpy="0 0 0"/>
      <material name="green"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${roda_radius}"/>
      </geometry>
    </collision>

    <!-- INERTIA (SPHERE) -->
    <xacro:sphere_inertia
        m="${roda_mass}"
        r="${roda_radius}"
        o_xyz="0 0 0"
        o_rpy="0 0 0"/>
  </link>

  <!-- ========================= -->
  <!--           JOINTS          -->
  <!-- ========================= -->

  <joint name="base_to_base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="mobile_uvc_base_link"/>
    <origin xyz="${-base_x} ${-base_y} ${-base_z}" rpy="0 0 0"/>
  </joint>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="mobile_uvc_base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="${base_x - left_wheel_x} ${base_y} ${base_z - wheel_z}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="mobile_uvc_base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="${base_x - right_wheel_x} ${base_y} ${base_z - wheel_z}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>

  <joint name="roda_joint" type="continuous">
    <parent link="mobile_uvc_base_link"/>
    <child link="roda_link"/>
    <origin xyz="${base_x - roda_x} ${base_y - roda_y} ${base_z - roda_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>
