<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="base_cylinder_height" value="0.060"/>
<xacro:property name="base_cylinder_radius" value="0.12"/>
<xacro:property name="slider_length" value="0.472"/>

<xacro:property name="mass_base_cylinder" value="1.5"/>
<xacro:property name="mass_rotary_bearing" value="1.0"/>
<xacro:property name="mass_waist_structure" value="3.0"/>

<xacro:property name="mass_slider_carriage" value="1.8"/>
<xacro:property name="mass_shoulder" value="2.0"/>
<xacro:property name="mass_elbow" value="1.7"/>
<xacro:property name="mass_wrist" value="1.1"/>
<xacro:property name="mass_finger" value="0.25"/>

<link name="arm_base_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/base.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="gray"/>
  </visual>

  <collision>
    <geometry>
      <cylinder radius="${base_cylinder_radius}" length="${base_cylinder_height}"/>
    </geometry>
  </collision>

  <xacro:cylinder_inertia 
      m="${mass_base_cylinder}"
      r="${base_cylinder_radius}"
      h="${base_cylinder_height}"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<link name="waist_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/waist.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0 ${-base_cylinder_height}" rpy="0 0 0"/>
    <material name="yellow"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.06 0.10 0.317"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_rotary_bearing + mass_waist_structure}"
      x="0.06"
      y="0.10"
      z="0.317"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<link name="slide_carriage_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/slider_carriage.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0 ${-slider_length - base_cylinder_height}" rpy="0 0 0"/>
    <material name="green"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.06 0.04 0.07"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_slider_carriage}"
      x="0.06"
      y="0.04"
      z="0.07"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>


<link name="shoulder_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/shoulder.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 -0.1212 ${-slider_length + base_cylinder_height - 2 * 0.09}" rpy="0 0 0"/>
    <material name="orange"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.12 0.04 0.06"/>
    </geometry>
    <origin xyz="0 -0.358 ${-slider_length + base_cylinder_height - 2 * 0.09}" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_shoulder}"
      x="0.12"
      y="0.04"
      z="0.06"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<link name="elbow_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/elbow.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 ${-0.48} ${-slider_length + base_cylinder_height - 2 * 0.09}" rpy="0 0 0"/>
    <material name="red"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.12 0.04 0.06"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_elbow}"
      x="0.12"
      y="0.04"
      z="0.06"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<link name="wrist_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/wrist.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0.639 0.17" rpy="${pi} 0 0"/>
    <material name="purple"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.055 0.06 0.04"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_wrist}"
      x="0.055"
      y="0.06"
      z="0.04"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<link name="left_finger_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/left_finger.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="-0.02 -0.639 0.06" rpy="0 ${pi} 0"/>
    <material name="red"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.017 0.037 0.04"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_finger}"
      x="0.017"
      y="0.037"
      z="0.04"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<link name="right_finger_link">
  <visual>
    <geometry>
      <mesh filename="file:///home/linos/cad_projects/gripper/right_finger.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0.02 -0.639 0.06" rpy="0 ${pi} 0"/>
    <material name="red"/>
  </visual>

  <collision>
    <geometry>
      <box size="0.017 0.037 0.04"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <xacro:box_inertia
      m="${mass_finger}"
      x="0.017"
      y="0.037"
      z="0.04"
      o_xyz="0 0 0"
      o_rpy="0 0 0"/>
</link>

<joint name="arm_base_to_mobile_base_link" type="fixed">
  <parent link="mobile_uvc_base_link"/>
  <child link="arm_base_link"/>
  <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<joint name="arm_base_to_waist" type="revolute">
  <parent link="arm_base_link"/>
  <child link="waist_link"/>
  <origin xyz="0 0 ${base_cylinder_height}" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${-pi* 5/6}" upper="${pi*5/6}" effort="50" velocity="1.0"/>
</joint>

<joint name="slide_carriage_to_slider" type="prismatic">
  <parent link="waist_link"/>
  <child link="slide_carriage_link"/>
  <origin xyz="0 0 ${base_cylinder_height + slider_length - 0.09 + 0.05}" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${-slider_length + 0.126}" upper="${0}" effort="50" velocity="0.1"/>
</joint>


<joint name="shoulder_to_slide_carriage" type="revolute">
  <parent link="slide_carriage_link"/>
  <child link="shoulder_link"/>
  <origin xyz="0 0.12124 0.06" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${-pi/2}" upper="${pi/2}" effort="50" velocity="1.0"/>
</joint>

<joint name="elbow_to_shoulder" type="revolute">
  <parent link="shoulder_link"/>
  <child link="elbow_link"/>
  <origin xyz="0 0.358 0" rpy="0 0 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${-pi/2}" upper="${pi/2}" effort="50" velocity="1.0"/>
</joint>

<joint name="wrist_to_elbow" type="revolute">
  <parent link="elbow_link"/>
  <child link="wrist_link"/>
  <origin xyz="0 0.16 -0.42" rpy="0 ${pi} 0"/>
  <axis xyz="0 0 1"/>
  <limit lower="${-pi/2}" upper="${pi/2}" effort="50" velocity="1.0"/>
</joint>

<joint name="left_finger_to_wrist" type="prismatic">
  <parent link="wrist_link"/>
  <child link="left_finger_link"/>
  <origin xyz="0.04728 0 0.1139" rpy="0 0 0"/>
  <axis xyz="1 0 0"/>
  <limit lower="0" upper="-0.08" effort="20" velocity="0.05"/>
</joint>

<joint name="right_finger_to_wrist" type="prismatic">
  <parent link="wrist_link"/>
  <child link="right_finger_link"/>
  <origin xyz="${-0.04728 -0.018} 0 0.1139" rpy="0 0 0"/>
  <axis xyz="1 0 0"/>
  <limit lower="0" upper="0.08" effort="20" velocity="0.05"/>
</joint>

</robot>